package com.budgetly.ui.dashboard

import androidx.navigation.NavDirections
import com.budgetly.R

/**
 * This file documents the NavDirections used by DashboardFragment.
 * These classes are auto-generated by the Navigation Safe Args Gradle plugin
 * at build time from nav_graph.xml — you do NOT need to create them manually.
 *
 * Safe Args plugin generates:
 *   - DashboardFragmentDirections.actionDashboardToExpenseDetail(expenseId: Long)
 *   - ExpensesFragmentDirections.actionExpensesToDetail(expenseId: Long)
 *   - MoreFragmentDirections.actionMoreToSubscriptions()
 *   - MoreFragmentDirections.actionMoreToBudget()
 *   - MoreFragmentDirections.actionMoreToSettings()
 *   - ExpenseDetailFragmentArgs (receives expenseId: Long)
 *
 * These are generated from navigation/nav_graph.xml <action> and <argument> tags.
 * To trigger generation: Build → Make Project (or ./gradlew generateSafeArgs)
 *
 * If you see "Unresolved reference: DashboardFragmentDirections", ensure:
 *   1. The navigation-safe-args-gradle-plugin is applied in root build.gradle
 *   2. The nav_graph.xml has correct <argument> tags
 *   3. Project has been built at least once
 */
object SafeArgsInfo
